version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_USER_PASSWORD}

  app-server:
    image: ghcr.io/a3510377/elder-care-app_server:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_CONN_STRING: mongodb://${DB_USERNAME}:${DB_USER_PASSWORD}@mongo:27017/
  
  app-frontend:
    image: ghcr.io/a3510377/elder-care-app_frontend:latest
    restart: always
    ports:
      - 80:3000
    environment:
      NUXT_PUBLIC_API_URL: XXX
